init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "1.0.0-g$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

build_script:
  - echo appveyor_build_version %appveyor_build_version%
#  - '"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
  - msbuild src/ext/BalExtension/wixstdba/wixstdba.sln /m /p:Configuration=Release

  - NuGet.exe pack -NonInteractive -Version %appveyor_build_version% Wix.WixStdBAMod.nuspec

artifacts:
  - path: 'src/ext/BalExtension/wixstdba/Release/WixStdBA.dll'
  - path: 'src/ext/BalExtension/wixstdba/Release/WixStdBA.pdb'
  - path: 'Wix.WixStdBAMod.$(appveyor_build_version).nupkg'

deploy:
  provider: S3
  access_key_id: AKIAIS47PXL2MYYR2HAA
  secret_access_key:
    secure: VxGmUlNpj45ISyJAKgX2/JcY6Ljlc3n7a/CCsMzWJ8JSqaxU+CtM8L+aReu9ehSq
  bucket: nuget-packages.metamorphsoftware.com
  region: us-east-1
  artifact: Wix.WixStdBAMod.$(appveyor_build_version).nupkg
  on:
    appveyor_repo_tag: true        # deploy on tag push only
